apiVersion: apps/v1
kind: pod
metadata:
  name: calculator
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: project
    spec:
      containers:
       - name: container1
         image: 316444450716.dkr.ecr.us-east-1.amazonaws.com/calculator-java:v1.0.0
         imagePullSecrets:
         - name: ecr-secret
         ports:
         - containerPort: 80

